### ISSUE TITLE
Documentation missing how to create a new instance of a class for each injection

### ISSUE THREAD

**Issue by DaveGUI** [unadlib/reactant#109]
Reactant has been working great for our dependency injection and viewmodules.  One thing we haven't figured out from Reactant's documentation, all classes/objects injected are effectively singletons because if 2 classes need the class Foo{}, they get the same instance of it if it already exists in the container.  With the constructor injection, how can it request a new object instead of a pre-existing one thats already in the container?  I'd prefer not to do useFactory in the modules as the class being injected does have a dependency of its own that is injected.

This might be good to add to the documentation.

For example, how can the 2 classes below, MainView and OtherView get their own instance of Foo?

```
@injectable({name:"foo"})
class Foo{
....
}

class MainView extends ViewModule {
   constructor(protected foo: Foo){   }
   component(....)
} 

class OtherView extends ViewModule {
   constructor(protected foo: Foo)  {   }
   component(....)
} 

I'd prefer to avoid:
modules: [
  { 
     provide: "foo",
     useFactory: ()=> {return new Foo(...);}
  }
]

As our Foo does have a dependency that Reactant is injecting
```

**Comment by unadlib** [comment]
In fact, you can use multiple instances simply by using different injection tokens, like this,

```ts
@injectable({name:"foo"})
class Foo{
....
}

class MainView extends ViewModule {
   constructor(@inject('foo1') protected foo: Foo){   }
   component(....)
} 

class OtherView extends ViewModule {
   constructor(@inject('foo1') protected foo: Foo)  {   }
   component(....)
} 
```

and 

```ts
modules: [
  {
    provide: 'foo0',
    useClass: Foo,
  },
  {
    provide: 'foo1',
    useClass: Foo,
  },
],
```

**Comment by unadlib** [comment]
hi, @DaveGUI , I have updated the related documentation about [dependency injection](https://reactant.js.org/docs/basic-tutorial/base-di).

**Comment by DaveGUI** [comment]
Thank you for adding that to the documentation!  In my specific case, I got a runtime error, I'm using a SharedTab type app and trying to have multiple instances of a ViewModule used by other ViewModules.  I'll see if using the Reactant-Share example I can demonstrate the same error and create a new issue if so.
