### ISSUE TITLE
Documentation missing on runtime object creation from container

### ISSUE THREAD

**Issue by DaveGUI** [unadlib/reactant#110]
Hi,

Assuming a typical createSharedApp() app, is there a way at runtime for a class to get (or create a new object) from the "main container" for the app?  Not sure if the following code is helpful, but typically if I do new Foo() on an object that uses @state/@action, I get errors even if I tried using @autobind:

Uncaught Error: 'this' in method 'AddFoos' of class 'FooList' decorated by '@action' must be bound to the current class instance.

I am guessing I need to get the object from the container and not do New on it so the @action function is correctly bound to the class.  Here is a simple example, although I understand the code could be changed to return a simple Array or Map instead of a FooList but trying to come up with a simple example of wanting to do New myClassName() at runtime instead of constructor injection; This could be good to also add to the documentation.

```
class Foo{
  @state
  Name: string = "";

  @state
   classifier: string = "";
}

class FooList
{
  @state
  Foos: Array<Foo> = [];
  
  @action
  UpdateFoos(foos: Array<Foo>){.....}
}

class FooView{
   constructor(inject("AllFoos") allFooList: FooList) {}

  get SpecialFoo(): FooList
  {
      const foolist = new FooList(); //This line would be replaced with getting a new FooList from the container...
     foolist.UpdateFoos(this.allFooList.filter((foo)=>......);
     return foolist;
  } 
}

```

Thank you

**Comment by unadlib** [comment]
@DaveGUI , you need the dynamic module injection feature. Here are docs of relevant [dynamic modules](https://reactant.js.org/docs/advanced-guides/dynamic-modules).

In your example, you can get a new instance of FooList this way.

```ts
class FooView{
  constructor(inject("AllFoos") allFooList: FooList) {}

  async getSpecialFoo(): FooList {
     const container = await load(this, [{ provide: 'newFooList', useClass: FooList }]);
     const foolist = container.get('newFooList');
     foolist.UpdateFoos(this.allFooList.filter((foo)=>......);
     return foolist;
  } 
}
```

**Comment by DaveGUI** [comment]
Thank you!  I didn't think to look under dynamic modules, I had been checking all the dependency injection pages.
