### ISSUE TITLE
Proposal: Optimizing @computed based on deps collection of signal concepts

### ISSUE THREAD

**Issue by unadlib** [unadlib/reactant#130]
### Relevant Package
- reactant-module

### Description
Since the access to a class's state is via a getter in Reactant, its derived state and that of computed can be implemented in a manner similar to the concept of signals for automatic dependency collection. 

The usage is modified as follows:

```diff
@injectable()
class Counter {
  @state
  count = 0;

-  @computed((that) => [that.count])
+  @computed
  get num() {
    return this.count + 1;
  }
}
```

**Comment by ZouYouShun** [comment]
sounds cool to me, but after that we may also need `untracked` method to be implement

https://angular.io/guide/signals#reading-without-tracking-dependencies

if we do that should have some method to
