### ISSUE TITLE
Next js integration. 

### ISSUE THREAD

**Issue by Astroner** [unadlib/reactant#22]
Is there a way to combine your Framework and Next Js to get a cool SSR?

**Comment by unadlib** [comment]
@Astroner Sorry for the late reply. That's what I've started to do recently.

**Comment by Astroner** [comment]
@unadlib np, good luck with it.

**Comment by unadlib** [comment]
hi @Astroner, Reactant already supports Next.js, the documentation is [here](https://reactant.js.org/docs/server-side-rendering).
