### ISSUE TITLE
Subscribe method from another module

### ISSUE THREAD

**Issue by Dadoudidou** [unadlib/reactant#23]
### Description

I try to subscribe a method from another module but it's not reached

### Minimal Reproduction

```typescript
// layout.view.tsx
@injectable()
export class LayoutView extends ViewModule {
    @state
    drawerOpen: boolean = false
    @action
    toggleDrawer(){ this.drawerOpen = !this.drawerOpen; }
   ...
```
```typescript
// parametres.service.ts
@injectable()
export class ParametresService {
    constructor(
        private readonly layout: LayoutView
    ){
        subscribe(this.layout, () => { console.log("this.layout.subscribe"); })
    }
   ...
```

### Expected Behavior
I expect that the method was called.

if i do this it work
```typescript
setTimeout(() => {
   subscribe(this.layout, () => { console.log("this.layout.subscribe"); })
},1)
```
But it's not very elegant.

Thanks

**Comment by unadlib** [comment]
@Dadoudidou  Sorry, the documentation about it has not been added yet, but you can see the [test cases](https://github.com/unadlib/reactant/blob/master/packages/reactant-module/test/core/subscriber.test.ts) for it.

From the submission example, you could use it like this:

```ts
// parametres.service.ts
@injectable()
export class ParametresService {
    constructor(
        private readonly layout: LayoutView
    ){
        subscribe(this, () => { console.log("this.layout.subscribe"); })
    }
   ...
```

Because `subscribe` API is a subscription to all state changes, it is essentially the same principle as redux's `store.subscribe`.

Also, it looks like you need an API that listens for all state changes in a module, right?

**Comment by Dadoudidou** [comment]
I may have misspoken. 

I want in the ParametresService class, execute a function when the state of the LayoutView class change.

With `subscribe(this, () => { console.log("this.layout.subscribe"); })`, the function is executed when the state of the class ParametresService is updated. But not when the state of the LayoutView class is updated.

Thats why i try `subscribe(this.layout, () => { console.log("this.layout.subscribe"); })`


I hope I was more specific

**Comment by unadlib** [comment]
I think you can use `watch` API.

For Example,

```ts
// parametres.service.ts
@injectable()
export class ParametresService {
    constructor(
        private readonly layout: LayoutView
    ){
        watch(this, () =>this.layout.drawerOpen, (newValue, oldValue) => { console.log("this.layout.drawerOpen", newValue); })
    }
   ...
```

**Comment by Dadoudidou** [comment]
Hello
I found what I was looking for.
`subscribe(this.layout, () => { console.log("layout state change"); })` is work for me. Before it's not working because the service was loaded in a plugin module loaded in the modules createApp.

Now the service is loaded in a viewModule and the function is called only when the state of LayoutView class changed.

Maybe later i make more tests

Thanks for your quick responses
